sudo: true
language: node_js
node_js:
  - 14 # use nodejs v14 LTS
cache:
  - npm
  - apt
  - yarn
branches:
  only:
    - master # build master branch only
install:
  - wget $pandoc
  - sudo dpkg -i pandoc*.deb
script:
  - hexo clean
  - hexo generate # generate static files
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GH_TOKEN
  keep-history: true
  on:
    branch: master
  local-dir: public